config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students do
    resources :addresses, only: [:create, :new]
  end

  resources :courses, only: [:index, :show]

  root to: 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :street
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip

  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
# A student
class Student < ApplicationRecord
  validates_presence_of :name

  has_many :addresses

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @student = Student.find(params[:student_id])
    @address.student = @student
    if @address.save
      flash[:success] = 'Added address!'
      redirect_to student_path(@address.student)
    else
      flash[:error] = 'There was an error adding the address.'
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @students = @course.students
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
# Controller for student routess
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    student = Student.new(student_params)
    if student.save
      flash[:success] = "#{student.name} added successfully!"
      redirect_to student_path(student)
    else
      flash[:error] = 'There was an error adding the student.r'
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student.update(student_params)

    if student.save
      flash[:success] = "#{student_params[:name]} updated successfully!"
      redirect_to student_path(student)
    else
      render :edit
    end
  end

  def destroy
    name = student.name
    if student.destroy
      flash[:success] = "#{name} was deleted successfully!"
      redirect_to students_path
    else
      flash[:error] = 'There was a problem in deleting the student.'
      render :student
    end
  end

  private

  def student
    Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>Add address for <%= @student.name %></h1>

<%= form_for [@student, @address] do |f| %>
  <%= f.text_field :description %>
  <%= f.text_field :street %>
  <%= f.text_field :city %>
  <%= f.text_field :state %>
  <%= f.text_field :zip %>

  <%= f.submit %>
<% end %>

app/views/courses/index.html.erb
<h1>Course List</h1>

<ul id="courses">
  <% @courses.find_each do |course| %>
    <li>
      <%= link_to "#{course.code} - #{course.name}", course_path(course), id: "course_#{course.id}" %>
    </li>
  <% end %>
</ul>

app/views/courses/show.html.erb
<h1><%= @course.code %> - <%= @course.name %></h1>
<h2>Students</h2>

<ul id="students">
  <% @students.find_each do |student| %>
    <li>
      <%= link_to student.name, student_path(student), id: "student_#{student.id}" %>
    </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Enrollment</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav>
  <ul class="top-nav">
    <%= render partial: 'shared/nav_link', locals: { href: students_path, text: 'Students' } %>
    <%= render partial: 'shared/nav_link', locals: { href: new_student_path, text: 'Create New Student' } %>
  </ul>
</nav>

app/views/shared/_nav_link.html.erb
<li>
  <%= link_to text, href %>
</li>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %></h1>

<%= render partial: 'students/form' %>

app/views/students/index.html.erb
<ul id="students">
  <% @students.find_each do |student| %>
    <li>
      <%= link_to student.name, student_path(student) %>
    </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render partial: 'students/form' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<%= link_to 'Edit', edit_student_path(@student) %>
<%= link_to 'Delete', student_path(@student), method: 'delete' %>

<h1>Addresses</h1>
<ul id="addresses">
  <% @student.addresses.find_each do |address| %>
    <li>
      <h3><%= address.description %></h3>
      <p><%= address.street %> <%= address.city %> <%= address.state%>, <%= address.zip %></p>
    </li>
  <% end %>
</ul>

<h1>Courses</h1>
<ul id="courses">
  <% @student.courses.find_each do |course| %>
    <li>
      <h3><%= course.code %></h3>
      <p><%= course.name %></p>
    </li>
  <% end %>
</ul>